# Name of the workflow
name: Release

# Run on every merge or commit to main
on: [push]

# Automatically create a GitHub Release, with release details specified
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest 
          prerelease: false
